const scale = (innerWidth + innerHeight) * .003;
console.log(scale)
export const data =  {  graphEditor:   {name:                   'graphEditor',
                                        class:                  'GraphEditor',
                                        minDistance:            10,
                                        sizeRemove:             30,
                        },     
                        vieport:       {name:                   'vieport',
                                        class:                  'Vieport',
                                        scale: {zoom:           1,
                                                min:            0.1,
                                                max:            10,
                                                step:           0.05},    
                        },
                        world:         {name:   'world',
                                        class:  'World',
                                        road:   {width:         50,
                                                current:        20,
                                                fill:           '#BBB',
                                                stroke:         '#BBB',
                                                lineWidth:       15,
                                                globalAlpha:    1,
                                                border:         {size:         2,
                                                                color:        'white',
                                                                globalAlpha:  1},
                                                marking:        {size:         1,
                                                                color:        'white',
                                                                globalAlpha:  .8,
                                                                dash:   {active:   true,
                                                                        line:     15,
                                                                        interval: 10}},
                                                point:          {color:        'white', 
                                                                radius:        5, 
                                                                globalAlpha:   .3},
                                        },
                                        building:       {width:         150,
                                                        minLenght:      150,
                                                        spacing:        50,
                                        }
                        },

                        primitives:    {point: {name:           'point',
                                                class:          'Point',
                                                point:          {radius: 10,
                                                                 color: 'blue',
                                                                 globalAlpha: 1},
                                                activePoint:    {radius: .8,
                                                                 color: 'yellow',
                                                                 globalAlpha: 1},
                                                lastPoint:      {width: .2,
                                                                 radius: .7,
                                                                 color: 'yellow',
                                                                 globalAlpha: 1}
                                        },
                                        segment:{name:         'segment',
                                                 class:        'Segment',
                                                 line:         {size:   4,
                                                                color: 'red',
                                                                globalAlpha: 1},
                                                 paint:        {size:   2,
                                                                color: 'yellow',
                                                                globalAlpha: 1},
                                                 dash:         {size:   1,
                                                                color:  'green',
                                                                length:  4,
                                                                interval: 2,
                                                                globalAlpha: 1}
                                        },
                                        polygon:{name:         'polygon',
                                                 class:         'Polygon', 
                                                 radius:        5,
                                                 color:         'red',
                                                 width:         2,
                                                 colorFill:     'rgba(0, 0, 255, .3)',
                                                 colorStroke:   'rgba(0, 0, 255, .3)',
                                                 globalAlpha:   .4,
                                        },
                                        envelope:{name:          'envelope',
                                                  class:         'Envelope', 
                                                  
                                                  colorFill:     '',
                                                  colorStroke:   '',
                                        },
                                
                        },
};
 